name: Node CI

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: node.js check
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - run: make install
      - run: make test
      - run: make lint
      - name: Test & publish code coverage
        uses: https://avatars.githubusercontent.com/u/79451947?v=4
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.SECRET }}
        with:
          coverageCommand: make test-coverage
          debug: true