name: Node CI

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: node.js check
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - run: make install
      - run: make test
      - run: make lint
      - name: Test & publish code coverage
        uses: Vandopal/codeclimate-action@v1
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.455e7d6789dab8ea5d47086ae009f76b06a4321c }}
        with:
          coverageCommand: make test-coverage
          debug: true